### ISSUE TITLE
Cannot install ddtrace 0.52.1 with Python 3.7

### ISSUE THREAD

**Issue by WillianTartaro** [DataDog/dd-trace-py#2837]
when I'm going to deploy the application, ddtrace gives an error

### Which version of dd-trace-py are you using?
0.52.1

### Which version of pip are you using?
pip version 18.1 (python 3.7)

### How can we reproduce your problem?
I'm adding ddtrace to the application, but when I deploy it, it gives this error

### What is the result that you get?

>   gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/usr/local/include/python3.7m -c ddtrace/profiling/collector/stack.c -o build/temp.linux-x86_64-3.7/ddtrace/profiling/collector/stack.o -DPy_BUILD_CORE
    ddtrace/profiling/collector/stack.c:643:30: fatal error: internal/pystate.h: No such file or directory
     #include <internal/pystate.h>
                                  ^
    compilation terminated.
    error: command 'gcc' failed with exit status 1

### What is the result that you expected?
I should be able to install ddtrace

**Comment by brettlangdon** [comment]
@WillianTartaro would you be willing to share the output from `pip debug --verbose` here?

What I am most interested in is what platform you are installing on. My guess would be alpine since it is installing from source distribution rather than a wheel, but I'd like to confirm (also so we can reproduce)

**Comment by P403n1x87** [comment]
@WillianTartaro The library requires a latest patch release of Python 3.7 to compile and work well (the library should compile with Python 3.7.3, but due to some ABI issues we recommend Python 3.7.8 as the minimum Python 3.7 release).

**Comment by WillianTartaro** [comment]
Sorry guys,

the resolution was to increase the python version, I put the 3.9 and it worked. Thanks.
