### ISSUE TITLE
[BUG]: Celery integration can't parse a list of broker URLs

### ISSUE THREAD

**Issue by rgs** [DataDog/dd-trace-py#12473]
### Tracer Version(s)

2.17.2+, 2.18.0+

### Python Version(s)

3.10.6

### Pip Version(s)

N/A

### Bug Report

If the Celery setup points to multiple brokers instead of a single one, the code introduced in commit b9573bed6d2ca4e956c3e20f2ae324651d8c6165 fails to parse the broker URLs, because it's expecting a single URL, not a list.
I would suggest to take the 1st URL in the list instead.

The error message that we get is an exception raised from `urllib._decode_args()`:
```
Signal handler "<function trace_after_publish at 0x7887ca7851b0>" raised: "AttributeError(\"'list' object has no attribute 'decode'\")"
```

**Comment by rachelyangdog** [comment]
Hello @rgs. Thanks for opening this issue. I've created a PR (#12496) to resolve this problem.

**Comment by PlugaruT** [comment]
@rachelyangdog can the fix be back-ported to v2 of the library? Seems that only v3 got the fix.
