### ISSUE TITLE
ddtrace 1.13.0 breaks sqlalchemy/psycopg3

### ISSUE THREAD

**Issue by sileht** [DataDog/dd-trace-py#5821]
### Summary of problem

After upgrade to ddtrace to 1.13.0 we have the following error:

```
AttributeError: 'IntegrationConfig' object has no attribute 'base_module'
  File "starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "ddtrace/contrib/asgi/middleware.py", line 260, in __call__
    reraise(exc_type, exc_val, exc_tb)
  File "six.py", line 719, in reraise
    raise value
  File "ddtrace/contrib/asgi/middleware.py", line 255, in __call__
    return await self.app(scope, receive, wrapped_send)
  File "starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "starlette/routing.py", line 66, in app
    response = await func(request)
  File "fastapi/routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "fastapi/routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
  File "xxx/web/subscriptions.py", line 91, in get_user_oauth_access_token
    user = await github_user.GitHubUser.get_by_id(session, github_account_id)
  File "xxxx/models/github_user.py", line 97, in get_by_id
    result = await session.execute(sqlalchemy.select(cls).where(cls.id == _id))
  File "sqlalchemy/ext/asyncio/session.py", line 338, in execute
    result = await greenlet_spawn(
  File "sqlalchemy/util/_concurrency_py3k.py", line 165, in greenlet_spawn
    result = context.throw(*sys.exc_info())
  File "sqlalchemy/orm/session.py", line 2231, in execute
    return self._execute_internal(
  File "sqlalchemy/orm/session.py", line 2116, in _execute_internal
    conn = self._connection_for_bind(bind)
  File "sqlalchemy/orm/session.py", line 1983, in _connection_for_bind
    return trans._connection_for_bind(engine, execution_options)
  File "<string>", line 2, in _connection_for_bind
    # Copyright (C) 2005-2023 the SQLAlchemy authors and contributors
  File "sqlalchemy/orm/state_changes.py", line 137, in _go
    ret_value = fn(self, *arg, **kw)
  File "sqlalchemy/orm/session.py", line 1110, in _connection_for_bind
    conn = bind.connect()
  File "sqlalchemy/engine/base.py", line 3264, in connect
    return self._connection_cls(self)
  File "sqlalchemy/engine/base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()
  File "sqlalchemy/engine/base.py", line 3288, in raw_connection
    return self.pool.connect()
  File "sqlalchemy/pool/base.py", line 452, in connect
    return _ConnectionFairy._checkout(self)
  File "sqlalchemy/pool/base.py", line 1268, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "sqlalchemy/pool/base.py", line 716, in checkout
    rec = pool._do_get()
  File "sqlalchemy/pool/impl.py", line 168, in _do_get
    with util.safe_reraise():
  File "sqlalchemy/util/langhelpers.py", line 147, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "sqlalchemy/pool/impl.py", line 166, in _do_get
    return self._create_connection()
  File "sqlalchemy/pool/base.py", line 393, in _create_connection
    return _ConnectionRecord(self)
  File "sqlalchemy/pool/base.py", line 678, in __init__
    self.__connect()
  File "sqlalchemy/pool/base.py", line 902, in __connect
    with util.safe_reraise():
  File "sqlalchemy/util/langhelpers.py", line 147, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "sqlalchemy/pool/base.py", line 898, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "sqlalchemy/engine/create.py", line 637, in connect
    return dialect.connect(*cargs, **cparams)
  File "sqlalchemy/engine/default.py", line 616, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
  File "sqlalchemy/dialects/postgresql/psycopg.py", line 689, in connect
    await_only(self.psycopg.AsyncConnection.connect(*arg, **kw))
  File "sqlalchemy/util/_concurrency_py3k.py", line 102, in await_only
    return current.driver.switch(awaitable)  # type: ignore[no-any-return]
  File "sqlalchemy/util/_concurrency_py3k.py", line 160, in greenlet_spawn
    value = await result
  File "ddtrace/contrib/psycopg/async_connection.py", line 51, in patched_connect_async
    pin = Pin.get_from(_config[module_name].base_module)
  File "ddtrace/internal/utils/attrdict.py", line 27, in __getattr__
    return object.__getattribute__(self, key)
```

### Which version of dd-trace-py are you using?

1.13.0

### Which version of pip are you using?

22.3.1

### Which libraries and their versions are you using?

<details>
  <summary>`pip freeze`</summary>
aiofiles==23.1.0
alembic==1.10.4
anyio==3.6.2
attrs==23.1.0
Authlib==1.2.0
beautifulsoup4==4.12.2
bytecode==0.14.1
cattrs==22.2.0
certifi==2023.5.7
cffi==1.15.1
charset-normalizer==3.1.0
click==8.1.3
cryptography==40.0.2
daiquiri==3.2.1
datadog==0.45.0
ddsketch==2.0.4
ddtrace==1.13.0
deepdiff==6.3.0
Deprecated==1.2.13
envier==0.4.0
fastapi==0.95.1
first==2.0.2
graphql-utils==0.4
greenlet==2.0.2
gunicorn==20.1.0
h11==0.14.0
h2==4.1.0
hiredis==2.2.3
honcho==1.1.0
hpack==4.0.0
httpcore==0.16.3
httptools==0.5.0
httpx==0.23.3
hyperframe==6.0.1
idna==3.4
imia==0.5.3
itsdangerous==2.1.2
Jinja2==3.1.2
jsonschema==4.17.3
Mako==1.2.4
markdownify==0.11.6
MarkupSafe==2.1.2
msgpack==1.0.5
mypy==1.2.0
mypy-extensions==1.0.0
opentelemetry-api==1.16.0
ordered-set==4.1.0
packaging==23.1
passlib==1.7.4
protobuf==4.23.0
psycopg==3.1.9
psycopg-binary==3.1.9
pycparser==2.21
pydantic==1.10.7
PyJWT==2.7.0
pyrsistent==0.19.3
python-dotenv==1.0.0
python-json-logger==2.0.7
python-multipart==0.0.6
PyYAML==6.0
redis==4.5.4
requests==2.30.0
rfc3986==1.5.0
sentry-sdk==1.22.2
setproctitle==1.2.3
six==1.16.0
sniffio==1.3.0
soupsieve==2.4.1
SQLAlchemy==2.0.12
SQLAlchemy-Utils==0.41.1
starlette==0.26.1
starsessions==2.1.1
tenacity==8.2.2
typing_extensions==4.5.0
urllib3==1.26.15
uvicorn==0.22.0
uvloop==0.17.0
voluptuous==0.13.1
watchfiles==0.19.0
websockets==11.0.3
wrapt==1.15.0
xmltodict==0.13.0
</details>

### How can we reproduce your problem?

We update the lib and make a SQL request.

### What is the result that you get?

The SQL request is not executed, and a backtrace is thrown.

### What is the result that you expected?

No backtrace

**Comment by CharlesPerrotMinotHCHB** [comment]
Same here. May have to revert our code because we're flying blind because of this currently (since only 1.13 support psycopg 3)

**Comment by wconti27** [comment]
@sileht @CharlesPerrotMinotHCHB  To continue using ddtrace v1.13.0 until we are able to issue a patch, can you kindly set `DD_TRACE_PSYCOPG_ENABLED=False`? This should bypass the error and restore tracing for the rest of integrations.

**Comment by CharlesPerrotMinotHCHB** [comment]
> @sileht @CharlesPerrotMinotHCHB To continue using ddtrace v1.13.0 until we are able to issue a patch, can you kindly set `DD_TRACE_PSYCOPG_ENABLED=False`? This should bypass the error and restore tracing for the rest of integrations.

Thank you! Works and fixes the app, although obviously it also disables the psycopg integration in Datadog, so isn't suited for production use. Can't wait for 1.13.3 to be released! Thank you for backporting the fix to 1.13.x @wconti27
