### ISSUE TITLE
[BUG]: AttributeError: 'Context' object has no attribute '_reactivate'

### ISSUE THREAD

**Issue by akursar** [DataDog/dd-trace-py#13409]
### Tracer Version(s)

3.7.0

### Python Version(s)

3.12

### Pip Version(s)

25.0.1

### Bug Report

After updating to 3.7.0, I observe this traceback:

```
AttributeError: 'Context' object has no attribute '_reactivate'
--
  | error closing trace
  | Traceback (most recent call last):
  | File "/usr/local/lib/python3.12/site-packages/ddtrace/_trace/span.py", line 806, in __exit__
  | self.finish()
  | File "/usr/local/lib/python3.12/site-packages/ddtrace/_trace/span.py", line 317, in finish
  | self._finish_ns(time_ns())
  | File "/usr/local/lib/python3.12/site-packages/ddtrace/_trace/span.py", line 329, in _finish_ns
  | cb(self)
  | File "/usr/local/lib/python3.12/site-packages/ddtrace/_trace/tracer.py", line 648, in _on_span_finish
  | active = self.current_span()
  | ^^^^^^^^^^^^^^^^^^^
  | File "/usr/local/lib/python3.12/site-packages/ddtrace/_trace/tracer.py", line 768, in current_span
  | active = self.context_provider.active()
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  | File "/usr/local/lib/python3.12/site-packages/ddtrace/_trace/provider.py", line 105, in active
  | return self._update_active(item)
  | ^^^^^^^^^^^^^^^^^^^^^^^^^
  | File "/usr/local/lib/python3.12/site-packages/ddtrace/_trace/provider.py", line 117, in _update_active
  | if new_active._parent is None and new_active._parent_context and new_active._parent_context._reactivate:
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  | AttributeError: 'Context' object has no attribute '_reactivate'
```

I *think* this is because `_reactivate` was added in https://github.com/DataDog/dd-trace-py/pull/13168 but it is not defined when Context is [unpickled](https://ddtrace.readthedocs.io/en/stable/advanced_usage.html?highlight=multiprocessing#tracing-across-processes), and the fix may be simply adding `_reactivate` to `__getstate__` / `__setstate__`
