### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'must_call_globals'

### ISSUE THREAD

**Issue by spolloni** [DataDog/dd-trace-py#8644]
### Summary of problem

I am essentially re-raising https://github.com/DataDog/dd-trace-py/issues/6659 since even though this issue was fixed in https://github.com/DataDog/dd-trace-py/pull/6669, a new flavor of the same issue was re-introduced with https://github.com/DataDog/dd-trace-py/pull/7678 since the code yet again assumes `self.execution_context.get_item("asm_env")` is never `None`. 

### Which version of dd-trace-py are you using?

`2.7.0`

### How can we reproduce your problem?

As mentionned in https://github.com/DataDog/dd-trace-py/pull/6669's description:

> The root cause of this issue is unknown.
There are no tests added here because we don't have a replication case.

### What is the result that you get?

```
Exception ignored in: <generator object asm_request_context_manager at 0x7f1a09acf840>
Traceback (most recent call last):
  File "/opt/conda/envs/pdal/lib/python3.11/site-packages/ddtrace/appsec/_asm_request_context.py", line 377, in asm_request_context_manager
    _end_context(resources)
  File "/opt/conda/envs/pdal/lib/python3.11/site-packages/ddtrace/appsec/_asm_request_context.py", line 406, in _end_context
    resources.finalise()
  File "/opt/conda/envs/pdal/lib/python3.11/site-packages/ddtrace/appsec/_asm_request_context.py", line 154, in finalise
    callbacks = GLOBAL_CALLBACKS.get(_CONTEXT_CALL, []) if env.must_call_globals else []
                                                           ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'must_call_globals'
```

**Comment by spolloni** [comment]
attempted a PR for this ☝️

**Comment by emmettbutler** [comment]
@spolloni Thanks for the report and the pull request! We'll check it out.

**Comment by christophe-papazian** [comment]
@spolloni Thank you for your contribution. I'll review it for ASM. 

I would prefer to understand the root cause of the problem, as it may be a symptoms of something wrong in our context handling. 
Can I get more data about this application? Is it using Flask? Is it possible to get a full trace stack of the exception?
Thanks!

**Comment by spolloni** [comment]
> I would prefer to understand the root cause of the problem, as it may be a symptoms of something wrong in our context handling.
> Can I get more data about this application? Is it using Flask? Is it possible to get a full trace stack of the exception?

@christophe-papazian  This is a FastAPI application. I poked around and was able to come up with an MRE and some (hopefully) useful insight. 

Dockerfile:
```
FROM python:3.10-slim-bookworm

WORKDIR /app

RUN pip install --quiet --no-cache-dir \
    fastapi==0.110.0 \
    uvicorn==0.27.1 \
    starlette==0.36.3 \
    ddtrace==2.7.0

COPY api/main.py ./api/main.py

ENV DD_APPSEC_ENABLED="true"

CMD ddtrace-run uvicorn api.main:app --host 0.0.0.0 --port 34542
```

with `main.py` as: 
```python
from fastapi import FastAPI, Response


app = FastAPI(debug=True)


@app.get(
    '/health',
    tags=['Service Status'],
    response_class=Response,
)
def get_health():
    return Response(
        content="Server is healthy!",
        media_type="text/plain",
    )


api_v1 = FastAPI(debug=True)
app.mount('/v1', api_v1)

```

Notice the mounting of the sub application in the last two lines ☝️. You can reproduce the trace I posted in my original comment by `curl`ing `http://localhost:34542/v1/`, while `http://localhost:34542/v2/` and `http://localhost:34542/health` give back 404 and 202 respectively.

**Comment by christophe-papazian** [comment]
Thank you so much for all the info, I'll be able to investigate from that.

**Comment by mabdinur** [comment]
[Fix](https://github.com/DataDog/dd-trace-py/pull/8654) will be released in v2.7.4

**Comment by spolloni** [comment]
@mabdinur https://github.com/DataDog/dd-trace-py/pull/8654 doesn't address the root cause of the issue. cc @christophe-papazian
