### ISSUE TITLE
[DDTrace==2.8.0] AttributeError: module 'langchain_community' has no attribute 'chat_models'

### ISSUE THREAD

**Issue by davidallada** [DataDog/dd-trace-py#8889]
### Summary of problem
We are using LangChain with the ChatOpenAI module. When running ChatOpenAI, we get a datadog error with 
```
AttributeError: module 'langchain_community' has no attribute 'chat_models'
```
This comes from 
```
ddtrace/contrib/langchain/patch.py:349
```
It seems like langchain-community <= 0.0.10 puts the chat_models in langchain-community, while > 0.0.10 instructs you to pip install `langchain-openai` and import from langchain_openai.
But datadog's codebase says that it should look at langchain_community for that file path.

In ddtrace, this line is the offender:
```
if isinstance(instance, BASE_LANGCHAIN_MODULE.chat_models.ChatOpenAI) or (
            langchain_openai and isinstance(instance, langchain_openai.ChatOpenAI)
        ):
```
The problem is that when checking the isinstance, python tries to complete the import. I believe the easiest solution is to just switch the two boolean checks.

```
if (
            langchain_openai and isinstance(instance, langchain_openai.ChatOpenAI)
        ) or isinstance(instance, BASE_LANGCHAIN_MODULE.chat_models.ChatOpenAI):
```
This wont fix the underlying issue of trying to grab an import when it does not exist, but it will not break it for the rest of us :)

Here is a proposed solution, I will also make a Pull Request if possible:
```
import importlib
def safe_isinstance(instance, base_module, module_suffix):
    """
    Checks if the module exists safely without throwing an error
    """
    base_module_name = getattr(base_module, "__name__")
    try:
        module = importlib.import_module(f"{base_module_name}.{module_suffix}")
    except (ModuleNotFoundError, ImportError):
        return False

    return isinstance(instance, module)

if safe_isinstance(instance, BASE_LANGCHAIN_MODULE, "chat_models.ChatOpenAI") or (
    langchain_openai and safe_isinstance(instance, langchain_openai, "ChatOpenAI")
):
```
And that should safely check if the module exists first and then check if the instance is an instance of that module so we fail gracefully

### Which version of dd-trace-py are you using?
`ddtrace==2.8.0`

### Which version of pip are you using?
`pip 24.0 from /usr/local/lib/python3.11/site-packages/pip (python 3.11)`

### Which libraries and their versions are you using?

<details>
  <summary>`pip freeze`</summary>
  ```
ddtrace==2.8.0
langchain==0.1.14
langchain-community==0.0.31
langchain-core==0.1.40
langchain-openai==0.1.1
langchain-pinecone==0.0.3
langchain-text-splitters==0.0.1
langdetect==1.0.9
langsmith==0.1.40
  ```
</details>

### How can we reproduce your problem?
We are using a docker container for python3.11, but you can use any linux distro (or local)
```
pip install ddtrace==2.8.0 langchain langchain-openai langchain-community python-dotenv
```
This requires a ddtrace api key and openai api key in the env vars
For reproduction, im using a simple 
```
ddtrace-run ipython
```
And then run 
```
from langchain_openai import ChatOpenAI
from langchain.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser
from langchain_core.runnables import RunnablePassthrough
from dotenv import load_dotenv
load_dotenv()
model = ChatOpenAI(model="gpt-4-turbo-preview")
chat_prompt = ChatPromptTemplate.from_messages(["What is 1 + 1?"])
retrieval_chain = (
    {"test": RunnablePassthrough()}
    | chat_prompt
    | model
    | StrOutputParser()
)
retrieval_chain.invoke("test")
```

### What is the result that you get?
And that raises
```
Error submitting packet: [Errno 111] Connection refused, dropping the packet and closing the socket
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[1], line 15
      8 chat_prompt = ChatPromptTemplate.from_messages(["What is 1 + 1?"])
      9 retrieval_chain = (
     10     {"test": RunnablePassthrough()}
     11     | chat_prompt
     12     | model
     13     | StrOutputParser()
     14 )
---> 15 retrieval_chain.invoke("test")

File /usr/local/lib/python3.11/site-packages/langchain_core/runnables/base.py:2499, in RunnableSequence.invoke(self, input, config)
   2497 try:
   2498     for i, step in enumerate(self.steps):
-> 2499         input = step.invoke(
   2500             input,
   2501             # mark each step as a child run
   2502             patch_config(
   2503                 config, callbacks=run_manager.get_child(f"seq:step:{i+1}")
   2504             ),
   2505         )
   2506 # finish the root run
   2507 except BaseException as e:

File /usr/local/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py:154, in BaseChatModel.invoke(self, input, config, stop, **kwargs)
    143 def invoke(
    144     self,
    145     input: LanguageModelInput,
   (...)
    149     **kwargs: Any,
    150 ) -> BaseMessage:
    151     config = ensure_config(config)
    152     return cast(
    153         ChatGeneration,
--> 154         self.generate_prompt(
    155             [self._convert_input(input)],
    156             stop=stop,
    157             callbacks=config.get("callbacks"),
    158             tags=config.get("tags"),
    159             metadata=config.get("metadata"),
    160             run_name=config.get("run_name"),
    161             **kwargs,
    162         ).generations[0][0],
    163     ).message

File /usr/local/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py:554, in BaseChatModel.generate_prompt(self, prompts, stop, callbacks, **kwargs)
    546 def generate_prompt(
    547     self,
    548     prompts: List[PromptValue],
   (...)
    551     **kwargs: Any,
    552 ) -> LLMResult:
    553     prompt_messages = [p.to_messages() for p in prompts]
--> 554     return self.generate(prompt_messages, stop=stop, callbacks=callbacks, **kwargs)

File /usr/local/lib/python3.11/site-packages/ddtrace/contrib/trace_utils.py:334, in with_traced_module.<locals>.with_mod.<locals>.wrapper(wrapped, instance, args, kwargs)
    332     log.debug("Pin not found for traced method %r", wrapped)
    333     return wrapped(*args, **kwargs)
--> 334 return func(mod, pin, wrapped, instance, args, kwargs)

File /usr/local/lib/python3.11/site-packages/ddtrace/contrib/langchain/patch.py:349, in traced_chat_model_generate(langchain, pin, func, instance, args, kwargs)
    346         span.set_tag_str("langchain.request.%s.parameters.%s" % (llm_provider, param), str(val))
    348 chat_completions = func(*args, **kwargs)
--> 349 if isinstance(instance, BASE_LANGCHAIN_MODULE.chat_models.ChatOpenAI) or (
    350     langchain_openai and isinstance(instance, langchain_openai.ChatOpenAI)
    351 ):
    352     _tag_openai_token_usage(span, chat_completions.llm_output)
    353     integration.record_usage(span, chat_completions.llm_output)

AttributeError: module 'langchain_community' has no attribute 'chat_models'
```
### What is the result that you expected?
Not to raise an exception

### Stack Trace
```
Traceback (most recent call last):
fastapi-1        |   File "/app/qclippy/fastapi/main.py", line 100, in ask_question
fastapi-1        |     chain_answer = gpt_qa_chain.invoke(
fastapi-1        |                    ^^^^^^^^^^^^^^^^^^^^
fastapi-1        |   File "/usr/local/lib/python3.11/site-packages/langchain_core/runnables/base.py", line 2499, in invoke
fastapi-1        |     input = step.invoke(
fastapi-1        |             ^^^^^^^^^^^^
fastapi-1        |   File "/usr/local/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 154, in invoke
fastapi-1        |     self.generate_prompt(
fastapi-1        |   File "/usr/local/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 554, in generate_prompt
fastapi-1        |     return self.generate(prompt_messages, stop=stop, callbacks=callbacks, **kwargs)
fastapi-1        |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
fastapi-1        |   File "/usr/local/lib/python3.11/site-packages/ddtrace/contrib/trace_utils.py", line 334, in wrapper
fastapi-1        |     return func(mod, pin, wrapped, instance, args, kwargs)
fastapi-1        |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
fastapi-1        |   File "/usr/local/lib/python3.11/site-packages/ddtrace/contrib/langchain/patch.py", line 349, in traced_chat_model_generate
fastapi-1        |     if isinstance(instance, BASE_LANGCHAIN_MODULE.chat_models.ChatOpenAI) or (
fastapi-1        |                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
fastapi-1        | AttributeError: module 'langchain_community' has no attribute 'chat_models'
```

**Comment by ZStriker19** [comment]
Hi @davidallada  thanks for reaching out. We'll take a look!

**Comment by scottberres-tr** [comment]
Similar to the above, does this fix also resolve this exception? We are seeing this after the upgrade to 2.8


 No module named 'langchain_openai'."

**Comment by Yun-Kim** [comment]
@scottberres-tr Hi there! This [fix](https://github.com/DataDog/dd-trace-py/pull/8839) should resolve that exception (raised if `langchain-openai` and `langchain-pinecone` are not installed on your environment).
It should be available in `ddtrace==2.8.1` or in the next minor release, in the meantime a potential workaround is to include `langchain-openai/langchain-pinecone` as dependencies in your applications.

**Comment by scottberres-tr** [comment]
Thanks for the quick response!
