### ISSUE TITLE
ddtrace 1.12.0 inaccurate versions

### ISSUE THREAD

**Issue by maxwsil** [DataDog/dd-trace-py#9770]
https://pypi.org/project/ddtrace/1.12.0/ says it's available for python 3.6, but I'm unable to run it

### Which version of dd-trace-py are you using?
1.12.0

### Which version of pip are you using?
unsure

### Which libraries and their versions are you using?
python 3.6

<details>
  <summary>`pip freeze`</summary>
  
</details>

### How can we reproduce your problem?
try to install ddtrace on python3.6

### What is the result that you get?
cannot import name get_args
https://docs.python.org/3/library/typing.html#typing.get_args
get_args was added in python 3.8

### What is the result that you expected?
ddtrace installs on python 3.6

I think considering python3.6 isn't really supported anymore, the documentation should probably just be updated to say ddtrace 1.12.0 and later don't actually support python3.6?

**Comment by emmettbutler** [comment]
Thanks for pointing this out, @maxwsil. It's strange because at the time 1.12.0 was released, it did work with Python 3.6. We'll update the documentation to reflect reality and possibly look into what happened to break compatibility.

**Comment by maxwsil** [comment]
thanks! Could be due to my local setup but looks like the typing get_args would be true for everyone. This isn't really an issue for me personally as I'm upgrading to python3.8 anyway
