### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'lower' with APPSEC enabled after update to 1.15.1

### ISSUE THREAD

**Issue by pvicente** [DataDog/dd-trace-py#6284]
### Summary of problem

```
builtins.AttributeError: 'NoneType' object has no attribute 'lower'
Traceback (most recent call last):
  File "/var/lang/lib/python3.10/site-packages/datadog_lambda/wrapper.py", line 214, in __call__
    self.response = self.func(event, context, **kwargs)
  File "/var/task/rs/entrypoint/lambda_http.py", line 30, in lambda_handler
    def lambda_handler(event: t.Any, context: LambdaContext) -> t.Optional[t.Any]:
  File "/var/lang/lib/python3.10/site-packages/ddtrace/contrib/aws_lambda/patch.py", line 115, in __call__
    self.response = self.func(*args, **kwargs)
  File "/var/task/rs/entrypoint/lambda_http.py", line 52, in lambda_handler
    return apig_wsgi.make_lambda_handler(wsgi_app, binary_support=True)(event, context)
  File "/var/lang/lib/python3.10/site-packages/apig_wsgi/__init__.py", line 90, in handler
    result = wsgi_app(environ, response.start_response)  # type: ignore [arg-type]
  File "/var/lang/lib/python3.10/site-packages/flask/app.py", line 2548, in __call__
    return self.wsgi_app(environ, start_response)
  File "/var/lang/lib/python3.10/site-packages/ddtrace/contrib/flask/helpers.py", line 28, in wrapper
    return func(pin, wrapped, instance, args, kwargs)
  File "/var/lang/lib/python3.10/site-packages/ddtrace/contrib/flask/patch.py", line 500, in traced_wsgi_app
    return middleware(environ, start_response)
  File "/var/lang/lib/python3.10/site-packages/ddtrace/contrib/wsgi/wsgi.py", line 169, in __call__
    req_span = self.tracer.trace(
  File "/var/lang/lib/python3.10/site-packages/ddtrace/tracer.py", line 855, in trace
    return self.start_span(
  File "/var/lang/lib/python3.10/site-packages/ddtrace/tracer.py", line 773, in _start_span
    p.on_span_start(span)
  File "/var/lang/lib/python3.10/site-packages/ddtrace/appsec/processor.py", line 250, in on_span_start
    ip = trace_utils._get_request_header_client_ip(headers, peer_ip, headers_case_sensitive)
  File "/var/lang/lib/python3.10/site-packages/ddtrace/contrib/trace_utils.py", line 219, in _get_request_header_client_ip
    tmp_ip_header_value = get_header_value(ip_header)
  File "/var/lang/lib/python3.10/site-packages/ddtrace/contrib/trace_utils.py", line 187, in get_header_value
    return _get_header_value_case_insensitive(headers, key)
  File "/var/lang/lib/python3.10/site-packages/ddtrace/contrib/trace_utils.py", line 94, in _get_header_value_case_insensitive
    if key.lower().replace("_", "-") == keyname:
AttributeError: 'NoneType' object has no attribute 'lower'
```

### Which version of dd-trace-py are you using?
1.15.1

### Which version of pip are you using?
pip 23.0.1 from /var/lang/lib/python3.10/site-packages/pip (python 3.10)

### Which libraries and their versions are you using?

<details>
  <summary>`pip freeze`</summary>
  
</details>

```
bash-4.2# pip freeze
aiohttp==3.8.4
aiosignal==1.3.1
amazon-textract-response-parser==0.1.42
apig-wsgi==2.15.0
async-timeout==4.0.2
attrs==22.2.0
Authlib==1.2.0
awslambdaric==2.0.4
awslambdaric-stubs==0.1.0
Babel==2.12.1
beautifulsoup4==4.11.1
boto3==1.26.79
boto3-stubs==1.26.135
botocore==1.29.79
botocore-stubs==1.29.57
build==0.10.0
bytecode==0.14.0
CacheControl==0.12.11
cachetools==5.3.0
cattrs==22.2.0
certifi==2022.12.7
cffi==1.15.1
charset-normalizer==3.0.1
cleo==2.0.1
click==8.1.3
crashtest==0.4.1
cryptography==39.0.1
datadog==0.44.0
datadog-lambda==4.75.0
ddsketch==2.0.4
ddtrace==1.15.1
decorator==5.1.1
Deprecated==1.2.14
distlib==0.3.6
dkimpy==1.0.5
dnspython==2.3.0
dulwich==0.21.3
ecdsa==0.18.0
email-validator==1.3.1
envier==0.4.0
et-xmlfile==1.1.0
exceptiongroup==1.1.0
expiringdict==1.2.2
filelock==3.9.0
Flask==2.2.2
Flask-Cors==3.0.10
frozenlist==1.3.3
future==0.18.3
google-api-core==2.11.0
google-auth==2.16.1
google-cloud-aiplatform==1.26.0
google-cloud-automl==2.10.1
google-cloud-bigquery==3.9.0
google-cloud-core==2.3.2
google-cloud-documentai==2.10.0
google-cloud-resource-manager==1.10.1
google-cloud-storage==2.7.0
google-crc32c==1.5.0
google-resumable-media==2.4.1
googleapis-common-protos==1.58.0
greenlet==2.0.1
grpc-google-iam-v1==0.12.6
grpcio==1.50.0
grpcio-status==1.50.0
hiredis==2.1.1
html5lib==1.1
hypothesis==6.79.1
hypothesis-jsonschema==0.22.1
idna==3.4
importlib-metadata==6.0.1
inflection==0.5.1
installer==0.7.0
itsdangerous==2.1.2
jaraco.classes==3.2.3
jeepney==0.8.0
Jinja2==3.1.2
jmespath==1.0.1
jsonpath-ng==1.5.3
jsonschema==4.17.3
keyring==23.13.1
launchdarkly-server-sdk==7.5.1
lockfile==0.12.2
MarkupSafe==2.1.2
marshmallow==3.19.0
money-parser==0.0.1
more-itertools==9.1.0
morph==0.1.5
msgpack==1.0.5
multidict==6.0.4
mypy==1.1.1
mypy-boto3-comprehend==1.26.21
mypy-boto3-s3==1.26.0.post1
mypy-boto3-sagemaker==1.26.57
mypy-boto3-secretsmanager==1.26.49
mypy-boto3-ses==1.26.0.post1
mypy-boto3-sesv2==1.26.0.post1
mypy-boto3-sns==1.26.69
mypy-boto3-sqs==1.26.0.post1
mypy-boto3-textract==1.26.17
mypy-extensions==1.0.0
ndg-httpsclient==0.5.1
numpy==1.24.1
objectpath==0.6.1
openai==0.27.2
openpyxl==3.0.10
opentelemetry-api==1.18.0
orjson==3.8.5
packaging==21.3
pandas==1.5.3
pdfkit==1.0.0
pexpect==4.8.0
Pillow==9.4.0
pkginfo==1.9.6
platformdirs==2.6.2
ply==3.11
poetry==1.4.2
poetry-core==1.5.2
poetry-plugin-export==1.3.1
price-parser==0.3.4
probableparsing==0.0.1
proto-plus==1.22.2
protobuf==4.23.3
psycopg2==2.9.5
ptyprocess==0.7.0
pusher==3.3.1
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycountry==22.3.5
pycparser==2.21
pydantic==1.10.7
pyinstrument==4.4.0
PyMuPDF==1.22.1
PyNaCl==1.5.0
pyOpenSSL==23.0.0
pyparsing==3.0.9
PyPDF2==1.28.6
pyproject_hooks==1.0.0
pyRFC3339==1.1
pyrsistent==0.19.3
python-crfsuite==0.9.8
python-dateutil==2.8.2
python-jose==3.3.0
python-redis-rate-limit==0.0.8
pytz==2022.7.1
PyYAML==6.0
rapidfuzz==2.15.1
redis==4.4.2
regex==2023.3.23
requests==2.28.2
requests-file==1.5.1
requests-toolbelt==0.10.1
rsa==4.9
Rtree==1.0.1
s3transfer==0.6.0
SecretStorage==3.3.3
semver==2.13.0
Shapely==1.8.5.post1
shellingham==1.5.0.post1
simplejson==3.17.2
six==1.16.0
sortedcontainers==2.4.0
soupsieve==2.3.2.post1
SQLAlchemy==1.4.46
sqlalchemy2-stubs==0.0.2a32
structlog==21.5.0
tenacity==8.2.0
tiktoken==0.3.2
tldextract==3.4.0
tomli==2.0.1
tomlkit==0.11.7
tqdm==4.64.1
trove-classifiers==2023.4.18
types-awscrt==0.16.4
types-s3transfer==0.6.0.post5
typing_extensions==4.4.0
urllib3==1.26.14
usaddress==0.5.10
validators==0.19.0
virtualenv==20.21.1
weaviate-client==3.12.0
webencodings==0.5.1
Werkzeug==2.2.2
wrapt==1.14.1
xlrd==2.0.1
xmltodict==0.13.0
yarl==1.8.2
zipp==3.15.0
```
### How can we reproduce your problem?
I have a lambda receiving http calls from AWS-Gateway this lambda has APMs and ASM enabled ( "DD_TRACE_ENABLED" : true  "DD_APPSEC_ENABLED" : true).

Lambda receives the following request headers.

```
headers
{
  CloudFront-Forwarded-Proto: https
  CloudFront-Is-Desktop-Viewer: True
  CloudFront-Is-Mobile-Viewer: False
  CloudFront-Is-SmartTV-Viewer: False
  CloudFront-Is-Tablet-Viewer: False
  CloudFront-Viewer-ASN: 14618
  CloudFront-Viewer-Country: US
  Host: jinwg5ftte.execute-api.eu-west-1.amazonaws.com
  User-Agent: Amazon CloudFront
  Via: 2.0 f03ced384777449538f7af55da0e2760.cloudfront.net (CloudFront), 1.1 25d9b5959eaa82bb18ee3f35e6bf34b4.cloudfront.net (CloudFront)
  X-Amz-Cf-Id: zRaWn4lMDcLCDMitFQOvDbI21NG05tX7GXPy945ErtZ5urhw6qE3ew==
  X-Amzn-Trace-Id: Root=1-64a697a9-2ebc14ef1aac805a55743f31
  X-Forwarded-For: 20.83.144.189, 64.252.68.152, 15.158.50.11
  X-Forwarded-Port: 443
  X-Forwarded-Proto: https
  x-request-id: e4af75fb-32d3-4525-b03a-44738c534da0
}
```
but APPSEC is passing the following to the chashed function

```
[DEBUG]	2023-07-06T10:30:01.465Z	0d72f3aa-cc1b-4ab7-b52c-bc1ec6784c4f	[dd.trace_id=17143057574028938172 dd.span_id=7235464274251788582]	_get_request_header_client_ip headers '{None: 'on', 'Cloudfront-Forwarded-Proto': 'https', 'Cloudfront-Is-Desktop-Viewer': 'true', 'Cloudfront-Is-Mobile-Viewer': 'false', 'Cloudfront-Is-Smarttv-Viewer': 'false', 'Cloudfront-Is-Tablet-Viewer': 'false', 'Cloudfront-Viewer-Asn': '14618', 'Cloudfront-Viewer-Country': 'US', 'Host': 'jinwg5ftte.execute-api.eu-west-1.amazonaws.com', 'User-Agent': 'Amazon CloudFront', 'Via': '2.0 f03ced384777449538f7af55da0e2760.cloudfront.net (CloudFront), 1.1 25d9b5959eaa82bb18ee3f35e6bf34b4.cloudfront.net (CloudFront)', 'X-Amz-Cf-Id': 'zRaWn4lMDcLCDMitFQOvDbI21NG05tX7GXPy945ErtZ5urhw6qE3ew==', 'X-Amzn-Trace-Id': 'Root=1-64a697a9-2ebc14ef1aac805a55743f31', 'X-Forwarded-For': '20.83.144.189, 64.252.68.152, 15.158.50.11', 'X-Forwarded-Port': '443', 'X-Forwarded-Proto': 'https', 'X-Request-Id': 'e4af75fb-32d3-4525-b03a-44738c534da0'}'
```

see ```None: 'on',``` as header not sure from where it's coming so I presume it's something added into headers at APPSEC trace level.

### What is the result that you get?
Not a exception

### What is the result that you expected?
Exception

**Comment by juanjux** [comment]
Does it happen with ASM disabled? We don't touch the headers AFAIK, only read them (I'm double checking anyway).

**Comment by pvicente** [comment]
> Does it happen with ASM disabled? We don't touch the headers AFAIK, only read them (I'm double checking anyway).
@juanjux with `"DD_APPSEC_ENABLED" : false` it does not happen

**Comment by christophe-papazian** [comment]
Trying to figure out the cause. This is probably irrelevant. Can we have the environment variables names available? Any one of them set to 'on'?

**Comment by pvicente** [comment]
> Trying to figure out the cause. This is probably irrelevant. Can we have the environment variables names available? Any one of them set to 'on'?

From terraform code my env is "cytora-proto"

```
    # Datadog instrumentation
    "DD_SITE" : "datadoghq.com"
    "DD_API_KEY_SECRET_ARN" : "arn:aws:secretsmanager:${var.region}:${var.account_id[var.environment]}:secret:${var.environment}/risk-stream/${var.dd_api_key[var.environment]}"
    "DD_TRACE_ENABLED" : true
    "DD_RUNTIME_METRICS_ENABLED" : true
    "DD_APPSEC_ENABLED" : true
    "DD_FLUSH_TO_LOG" : true
    "DD_TRACE_DEBUG" : false
    "DD_PROFILING_ENABLED" : var.environment == "cytora-proto" ? true : false
    "DD_PROFILING_IGNORE_PROFILER" : true
    "DD_PROFILING_ENABLE_CODE_PROVENANCE" : true
    "DD_CAPTURE_LAMBDA_PAYLOAD" : var.environment == "cytora-proto" ? true : false
    "DD_ENV" : var.environment
    "DD_SERVICE" : var.service
```
