### PR TITLE
fix(tracer/writer): lock the connection

### PR DESCRIPTION
**Pull request by Kyle-Verhoog**
There existed a critical section with the connection object on writer as
the `periodic` logic of the writer could be invoked from the periodic
writer thread as well as from other threads calling `periodic`
(`tracer.flush()` or `tracer.shutdown()`). The critical section would
result in corrupted http connections. This bug was introduced in #2999.

The solution is to lock the connection when used. I don't suspect that
this would lead to any performance degradation for the vast majority of
users since there is little overhead added to the writer. A degradation
would occur if contending threads were calling `periodic()` as now the
connection is a shared resource.

Example symptom of the error if a race were to occur:
```
        except Exception as e:
            # Even though it's unlikely any traces have been sent, make the
            # final request to the test agent so that the test case is finished.
            conn = httplib.HTTPConnection(parsed.hostname, parsed.port)
            conn.request("GET", "/test/session/snapshot?ignores=%s&test_session_token=%s" % (",".join(ignores), token))
            conn.getresponse()
>           pytest.fail("Unexpected test failure during snapshot test: %s" % str(e), pytrace=True)
E           Failed: Unexpected test failure during snapshot test: 'NoneType' object has no attribute 'getresponse'
```

## Future

- If a manual flush is forced then use a new connection
- Connection pooling (maybe via https://urllib3.readthedocs.io/en/latest/reference/urllib3.connectionpool.html)

### CODE REVIEW

**Comment by brettlangdon** [comment]
Do you remember the specific execution that caused the bug to surface?

We should only have 1 writer thread per-process, but `_put()` can get called out of sync with `periodic()` because of manual flushing or retries? (I cannot remember)

**Comment by Kyle-Verhoog** [comment]
Yeah I tried to outline this in the PR description:

> There existed a critical section with the connection object on writer as
the periodic logic of the writer could be invoked from the periodic
writer thread as well as from other threads calling periodic
(tracer.flush() or tracer.shutdown()). The critical section would
result in corrupted http connections. This bug was introduced in https://github.com/DataDog/dd-trace-py/pull/2999.

let me know if this isn't clear and I can reword

**Review by brettlangdon — APPROVED** [review]

**Review by brettlangdon — DISMISSED** [review]

**Review by majorgreys — COMMENTED** [review]
Can we document why this connection lock is necessary in the code (basically a gist of the PR description)?

**Review by brettlangdon — APPROVED** [review]

**Review by brettlangdon — APPROVED** [review]

**Review by majorgreys — APPROVED** [review]
