### PR TITLE
chore(asyncpg): make _unpatch tolerant of partial patch state and wrapt 2.2.0

### PR DESCRIPTION
**Pull request by christophe-papazian**
APPSEC-65691

## Summary

`dd-gitlab/contrib/asyncpg 2/2` has been failing reliably on `main` since #18199, with two distinct errors in `_unpatch` exposed by the new `test_execute_after_patch_unpatch_patch` (which now calls `unpatch()` as its very first statement, without going through `patched_conn` first):

1. **`AttributeError: 'function' object has no attribute '__wrapped__'`** at `unwrap(asyncpg, "connect")` — `_unpatch` was asymmetric: the Protocol-methods loop already guarded with `iswrapped(...)` (#18139), but the `connect` unwrap ran unconditionally. Reachable any time `_datadog_patch=True` while `asyncpg.connect` is not actually wrapped.
2. **`TypeError: descriptor 'execute' for 'asyncpg.protocol.protocol.BaseProtocol' objects doesn't apply to a 'NoneType' object`** at `iswrapped(asyncpg.protocol.Protocol, method)` — the wrapt 2.2.0 regression (`FunctionWrapper.__get__` calls the inner Cython `method_descriptor`'s `tp_descr_get` with `Py_None` instead of `NULL`). `iswrapped` triggers it because it does `getattr(Protocol, "execute")`.

### Fixes

- **commit 1**: guard `unwrap(asyncpg, "connect")` with `iswrapped(asyncpg, "connect")`, matching the existing guard for Protocol methods.
- **commit 2**: replace `iswrapped(Protocol, method)` with `method in Protocol.__dict__` — a plain dict lookup that bypasses the descriptor protocol entirely. Same pattern (and comment) as `kafka._safe_unwrap` (`ddtrace/contrib/internal/kafka/patch.py:137-149`), which documents this exact wrapt 2.2.0 case.

Production behavior is unchanged. `_unpatch` is now tolerant of partial patch state and safe against the wrapt 2.2.0 descriptor read.

## Test plan

- [ ] `dd-gitlab/contrib/asyncpg 2/2` job goes green on this branch.
- [ ] Existing `test_patch_unpatch_asyncpg`, `test_unpatch_removes_method_shadow`, `test_patch_unpatch_patch_cycle`, `test_execute_after_patch_unpatch_patch` still pass.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

File: ddtrace/contrib/internal/asyncpg/patch.py [hunk 1]
```diff
@@ -176,13 +176,20 @@ def patch() -> None:
...
+        # iswrapped/getattr access reads the descriptor; under wrapt 2.2.0,
+        # FunctionWrapper.__get__ calls the inner Cython method_descriptor's tp_descr_get
+        # with Py_None instead of NULL, raising:
+        #   TypeError: descriptor 'execute' for 'asyncpg.protocol.protocol.BaseProtocol'
+        #              objects doesn't apply to a 'NoneType' object
+        # vars()/__dict__ lookup and delattr bypass the descriptor entirely.
+        # Using delattr (rather than setattr to the original) also avoids leaving a Cython
+        # descriptor shadow in Protocol.__dict__ that a later patch() would re-wrap instead
+        # of resolving the method naturally via MRO from BaseProtocol.
+        if method in asyncpg.protocol.Protocol.__dict__:
```
Comment (brettlangdon) [inline ddtrace/contrib/internal/asyncpg/patch.py:192]: I do worry about this a bit, since if asyncpg ever decides to override one of the base methods on Protocol, then this is going to break things for asyncpg


but also, unpatch never gets called in production code paths so maybe it is only a problem for our CI.... not sure, feels weird, but probably ok

**Review by avara1986 — APPROVED** [review]

**Review by brettlangdon — APPROVED** [review]
As long as we consider my comment, this lgtm, not a blocker

File: ddtrace/contrib/internal/asyncpg/patch.py (hunk 1 above)
Comment (christophe-papazian) [reply ddtrace/contrib/internal/asyncpg/patch.py:192]: Fair concern, but I think this PR doesn't actually change the risk surface :
the delattr behavior was already what #18139 introduced. 

This PR only swaps the existence check from `iswrapped(Protocol, method)` (which calls `getattr`, hitting the wrapt 2.2.0 descriptor regression) to method in `Protocol.__dict__`. Both checks behave identically today because Protocol inherits all of execute/bind_execute/query/bind_execute_many from the Cython BaseProtocol They never appear in `Protocol.__dict__` until _patch puts our wrapper there. 

test_unpatch_removes_method_shadow pins that assumption.

If asyncpg ever adds a Python-level override on Protocol, both this and the existing #18139 code would silently drop it on unpatch. The proper fix at that point would be to stash the pre-patch `Protocol.__dict__` entry in _patch and restore it in _unpatch.  
Since unpatch is only ever called in our tests, it's probably fine to leave as-is and revisit if/when asyncpg's Protocol gains an override

Comment (brettlangdon) [reply ddtrace/contrib/internal/asyncpg/patch.py:192]: Well, I don't think it changes the risk surface much since this code is only ever called from our test suite (more than anything else)
