### ISSUE TITLE
0.37.0 fails to build on Alpine Linux 3.9

### ISSUE THREAD

**Issue by dmarkey** [DataDog/dd-trace-py#1388]
Thanks for taking the time for reporting an issue!

Before reporting an issue on dd-trace-py, please be sure to provide all
necessary information.

If you're hitting a bug, make sure that you're using the latest version of this
library.

### Which version of dd-trace-py are you using?
0.37.0
### Which version of the libraries are you using?

This was building a wheel of ddtrace only
You can copy/paste the output of `pip freeze` here.

### How can we reproduce your problem?
pip wheel ddtrace==0.37.0
### What is the result that you get?
```
 gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Os -fomit-frame-pointer -g -Os -fomit-frame-pointer -g -Os -fomit-frame-pointer -g -DTHREAD_STACK_SIZE=0x100
000 -fPIC -I/usr/include/python3.6m -c ddtrace/profiling/collector/stack.c -o build/temp.linux-x86_64-3.6/ddtrace/profiling/collector/stack.o -DPy_BUILD_CORE
  ddtrace/profiling/collector/stack.c: In function '__Pyx_PyInt_As_pthread_t':
  ddtrace/profiling/collector/stack.c:8505:58: error: arithmetic on pointer to an incomplete type
       const pthread_t neg_one = (pthread_t) ((pthread_t) 0 - (pthread_t) 1), const_zero = (pthread_t) 0;
                                                            ^
  ddtrace/profiling/collector/stack.c:8428:47: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
               if (unlikely(value != (func_type) (target_type) value)) {\
                                                 ^
  ddtrace/profiling/collector/stack.c:808:43: note: in definition of macro 'unlikely'
     #define unlikely(x) __builtin_expect(!!(x), 0)
                                             ^
  ddtrace/profiling/collector/stack.c:8421:5: note: in expansion of macro '__PYX__VERIFY_RETURN_INT'
       __PYX__VERIFY_RETURN_INT(target_type, func_type, func_value, 0)
       ^~~~~~~~~~~~~~~~~~~~~~~~
  ddtrace/profiling/collector/stack.c:8526:26: note: in expansion of macro '__PYX_VERIFY_RETURN_INT'
                   case  1: __PYX_VERIFY_RETURN_INT(pthread_t, digit, digits[0])
```
### What is the result that you expected?
That it builds.
