### PR TITLE
chore(profiling): include <functional> in native_call_tracker

### PR DESCRIPTION
**Pull request by r1viollet**
## Description

`native_call_tracker` exposes `std::optional<std::reference_wrapper<NativeCallEntry>>` in its public API (header) and uses `std::ref` in its implementation (.cpp). Both symbols live in `<functional>`.

On the libstdc++ shipped with the manylinux image CI uses, `<functional>` is transitively pulled in via `<unordered_map>` / `<optional>` / `<type_traits>`, so the missing include went unnoticed. On stock Ubuntu 22.04 + gcc 11.4 it is **not** transitively included, and the build fails with:

```
error: 'ref' is not a member of 'std'
error: invalid use of incomplete type 'class std::reference_wrapper<...>'
error: 'value' is not a member of 'std::is_trivially_copy_constructible<std::reference_wrapper<...>>'
```

Include `<functional>` directly in both translation units that name those symbols (IWYU: include what you use):

- **`native_call_tracker.hpp`** — `lookup()` returns `std::optional<std::reference_wrapper<NativeCallEntry>>`, so the header owns the `<functional>` dependency.
- **`native_call_tracker.cpp`** — independently calls `std::ref(...)`. Even though it would transitively get `<functional>` via the header today, the .cpp shouldn't silently break if the header's public API ever stops needing `reference_wrapper`.

## Motivation

Unblock local builds on Ubuntu 22.04 / stock gcc 11 toolchains. Pre-existing latent bug introduced in #16751.

## Change Type

- [x] Bug fix (non-breaking change which fixes an issue)

## Testing

- CI (manylinux): no behavior change, headers already transitively included `<functional>`.
- Local Ubuntu 22.04 + gcc 11.4.0: `python setup.py build_ext --inplace` now compiles `dd_wrapper` successfully (was failing on `native_call_tracker.cpp` before this change).

No runtime behavior change; this is a build-portability fix.

### CODE REVIEW

**Review by KowalskiThomas — APPROVED** [review]
TY!
