### ISSUE TITLE
[BUG]: Nested closures over FastAPI Depends() args resolve to bare `cell` objects under ddtrace 4.8.x (worked on 3.12.2)

### ISSUE THREAD

**Issue by Alavi1412** [DataDog/dd-trace-py#19204]
### Tracer Version(s)

4.8.2

### Python Version(s)

Python 3.12 (slim-bookworm)

### Pip Version(s)

uv 0.11.11

## Summary

After upgrading `ddtrace` from **3.12.2 → 4.8.2**, nested async closures inside FastAPI route handlers that close over `Depends()`-injected parameters fail with:

`AttributeError: 'cell' object has no attribute '<method>'`

Valid Python should never expose a bare `cell` as the value of a free variable (`LOAD_DEREF` should return `cell.cell_contents`). This looks like closure corruption introduced by ddtrace 4.x instrumentation/wrapping.

We cannot downgrade (dependency policy). Worked around at the call site with `functools.partial`.

## Environment

| | |
|---|---|
| ddtrace (broken) | **4.8.2** |
| ddtrace (last known good) | **3.12.2** |
| Python | 3.12 |
| FastAPI | 0.136.x |
| Uvicorn | 0.34.x |
| Runtime | Linux containers (ECS), `ddtrace` APM enabled |

## Minimal reproduction

```python
from typing import Annotated

from fastapi import Depends, FastAPI

app = FastAPI()


class Service:
    async def do_work(self) -> dict:
        return {"ok": True}


def get_service() -> Service:
    return Service()


@app.get("/example")
async def example(
    *,
    service: Annotated[Service, Depends(get_service)],
):
    async def nested():
        # Under ddtrace 4.8.2, `service` is a bare `cell` here
        return await service.do_work()

    return await nested()
```

Run with ddtrace enabled (`ddtrace-run uvicorn ...` or equivalent library injection) on **4.8.2** and `GET /example`.

### Expected

`nested()` successfully calls `Service.do_work` (as on ddtrace **3.12.2**).

### Actual

```text
AttributeError: 'cell' object has no attribute 'do_work'

  File "...", line N, in nested
      return await service.do_work()
                   ^^^^^^^^^^^^^^^
```

## Evidence

- Zero occurrences on **3.12.2**.
- Started immediately after deploying **4.8.2**.
- Reproduces whenever the nested closure runs and reads a `Depends()`-injected object via a free variable.
- Binding the same call with `functools.partial(...)` (no freevars) avoids the failure entirely.

## Workaround

```python
from functools import partial

# Bind on the partial — no freevar cells
callback = partial(service.do_work)
return await callback()
```

Default-argument capture on the nested function also avoids the freevar path:

```python
async def nested(_service: Service = service):
    return await _service.do_work()
```

## Related

- https://github.com/DataDog/dd-trace-py/issues/8427 — profiler seeing `cell` during stack unwind (different symptom, similar “cell leaked” theme)

**Comment by P403n1x87** [comment]
@Alavi1412 thanks for the report. Based on what you have reported, I don't think you have tested the latest release of ddtrace? [The fix](https://github.com/DataDog/dd-trace-py/pull/18189) is contained in 4.11. The AI agent must have missed that in its analysis 😅.

**Comment by Alavi1412** [comment]
Yes, after posting it, we upgraded and the issue went away. Thanks.
