### PR TITLE
chore(waf): fix block_config compatibility

### PR DESCRIPTION
**Pull request by avara1986**
Adds a `.get()` method to the `Block_config` class to restore dictionary-like API compatibility broken by PR #15042, fixing Lambda integration failures.

PR #15042 changed `Block_config` from a dictionary to a class, introducing a breaking API change that caused Lambda integration to fail with:

```
AttributeError: 'Block_config' object has no attribute 'get'
Traceback (most recent call last):
  File "./python/lib/python3.13/site-packages/datadog_lambda/wrapper.py", line 187, in __call__
  File "./python/lib/python3.13/site-packages/datadog_lambda/asm.py", line 220, in get_asm_blocked_response
AttributeError: 'Block_config' object has no attribute 'get'
```

Rollback this ST PR after the merge https://github.com/DataDog/system-tests/commit/f87f4dd5c5d152007a1c022d8338c102c63f6ea1

APPSEC-59959

### CODE REVIEW

File: tests/appsec/appsec/test_appsec_utils.py [hunk 1]
```diff
@@ -84,3 +84,114 @@ def test_get_blocked_template_user_file_exists_json():
...
+    config = Block_config(
+        type="json",
+        status_code=404,
+        grpc_status_code=5,
+        security_response_id="custom-block-id",
+        location="/custom/location",
+    )
+
+    # Test all standard attributes
+    assert config.get("block_id") == "custom-block-id"
```
Comment (jandro996) [inline tests/appsec/appsec/test_appsec_utils.py:139]: Heads up, `block_id` is no longer correct. It changed a few weeks ago. Per LastPass [P1] “Blocking response identification” ([RFC](https://docs.google.com/document/d/1JJqsyxJgCKM0LqGE6Pg1ez3O-XB9bPdeejmme5Wf8jY/edit?tab=t.0) and [ST](https://github.com/DataDog/system-tests/pull/5517)), the new name is security_response_id.

**Review by christophe-papazian — APPROVED** [review]

File: tests/appsec/appsec/test_appsec_utils.py (hunk 1 above)
Comment (christophe-papazian) [reply tests/appsec/appsec/test_appsec_utils.py:139]: I can confirm, this is  still `block_id` also in our internal api.
