### PR TITLE
[WIP] chore(ray): add configure_logging helper to pass to Ray worker_process_setup_hook

### PR DESCRIPTION
**Pull request by imran-at-datadog**
[square.py](https://github.com/user-attachments/files/23723829/square.py)

## Description

This PR adds a helper function to add a JSON-formatting handler to the root logger and clear all other handlers which can be passed to Ray's worker_process_setup_hook on ray.init to configure logging on other libraries of interest such as PyTorch, for example:

```
import logging

import ddtrace
import ray

# Create a lambda function that wraps configure_logging with arguments
configure_logging_with_args = lambda: ddtrace.contrib.ray.configure_logging(logging.INFO)

# Initialize Ray with the setup hook
ray.init(
    runtime_env={"worker_process_setup_hook": configure_logging_with_args},
    logging_config=ray.LoggingConfig(
        encoding="JSON",
        log_level="INFO",  
        additional_log_standard_attrs=['name']
    )
)
```

This helper function is **NOT applied by default**, so the user can decide whether it is appropriate for their specific needs. For example if the user has other tools expecting a specific log format they may not want to apply this.

However, we believe in most cases the user will want to format logs as JSON to enable tracer context injection and correlation with traces in the Dist AI Obs UI.

The `encoding="JSON"` in logging_config only appear to affect messages directly emitted by the Ray logger - However most interesting messages for practical jobs are usually emitted by the main backend libraries used in the job, such as PyTorch, etc.

Passing this function to worker_process_setup_hook results in it running **LATE** in the worker setup process, and unlike attempting the same thing in the --tracing-startup-hook (which runs early in the worker process setup) this configuration does not get blown away by Ray or third party libraries attempting something similar. [According to the Ray docs](https://docs.ray.io/en/latest/ray-observability/user-guides/configure-logging.html#using-ray-logger-for-application-logs), a worker_process_setup_hook is the recommended way to configure logging.

## Testing

- [ ] Repeat tests

When launching jobs with `ray job submit --submission-id="imran-ray-logs-test-w-config" --runtime-env-json '{"worker_process_setup_hook": "ddtrace.contrib.ray.configure_logging"}' -- python ~/scripts/square.py` instead of passing the hook in ray.init, and without ray.init at the top of the job script, jobs currently fail with:

```
Traceback (most recent call last):
  File "/Users/imran.hendley/scripts/square.py", line 29, in <module>
    print(ray.get(futures))
          ^^^^^^^^^^^^^^^^
  File "/Users/imran.hendley/go/src/github.com/DataDog/dd-trace-py/ddtrace/contrib/internal/ray/patch.py", line 306, in traced_get
    return wrapped(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/imran.hendley/.pyenv/versions/ray/lib/python3.12/site-packages/ray/_private/auto_init_hook.py", line 22, in auto_init_wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/imran.hendley/.pyenv/versions/ray/lib/python3.12/site-packages/ray/_private/client_mode_hook.py", line 104, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/imran.hendley/.pyenv/versions/ray/lib/python3.12/site-packages/ray/_private/worker.py", line 2961, in get
    values, debugger_breakpoint = worker.get_objects(
                                  ^^^^^^^^^^^^^^^^^^^
  File "/Users/imran.hendley/.pyenv/versions/ray/lib/python3.12/site-packages/ray/_private/worker.py", line 1026, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(TypeError): ray::square() (pid=14256, ip=127.0.0.1)
TypeError: square() got an unexpected keyword argument '_dd_ray_trace_ctx'

```
## Risks

Minimal, since this is off by default.

### CODE REVIEW

File: ddtrace/contrib/ray.py [hunk 1]
```diff
@@ -18,3 +19,19 @@ def setup_tracing():
...
         tracing_helper._global_is_tracing_enabled = False
+
+
+def configure_logging(log_level=None):
+    root_logger = logging.getLogger()
+    if log_level:
+        root_logger.setLevel(log_level)
+
+    if root_logger.hasHandlers():
+        root_logger.handlers.clear()
```
Comment (yshapiro-57) [inline ddtrace/contrib/ray.py:30]: Will the code not work correctly if we add the new stream handler without clearing the old ones?

File: .riot/requirements/128409e.txt [hunk 2]
```diff
@@ -2,66 +2,67 @@
 # This file is autogenerated by pip-compile with Python 3.13
 # by the following command:
 #
-#    pip-compile --allow-unsafe --no-annotate .riot/requirements/4dc83b1.in
+#    pip-compile --allow-unsafe --no-annotate .riot/requirements/128409e.in
```
Comment (yshapiro-57) [inline .riot/requirements/128409e.txt:5]: If you merge the latest version of prod, will the need to regenerate these requirements files go away, or are they still out of sync in trunk?

**Review by yshapiro-57 — COMMENTED** [review]
@imran-at-datadog I ran a couple of local tests and was able to reproduce your success with getting the trace ID included in the customer logs. This is very promising, thank you for pushing this forward!

For the first test that I ran with this syntax:
```
    logging.basicConfig(level=logging.INFO)
    worker_logger = logging.getLogger(__name__)
    worker_logger.info(f"Calculating square for: {x}")
```
the call of `logging.basicConfig` from the customer code seemed to unset the settings you set that cause the trace ID to be written to the logs. I am now thinking that unlike traces, where we monkeypatch the Ray Core code with a high level of confidence that it won't break, for logs it might be better to not mess with the customer's setup and instead give them an option to explicitly send log lines to Datadog if they choose:

```
from ddtrace.contrib.ray import get_dd_ray_logger

dd_logger = get_dd_ray_logger()
dd_logger.warning("Calculating square of 42")
```

We can then either figure out how to update the Vector config to ignore all log lines that are not in the JSON format or do not explicitly include a trace ID, so that Vector only sends us the lines in this JSON format, or we could even have our logger write to a separate file in /tmp/ray/session_latest/logs to avoid mixing our log lines with the ones that aren't going to Datadog. What do you think, am I overengineering it with this suggestion?
